dist: trusty
sudo: required

language: php

php:
  - 7.2

services:
  - postgresql

addons:
  postgresql: "9.6"
env:
  global:
  - PGPORT=5432

before_install: phpenv config-add php_config.ini

install:
  - composer require phpunit/phpunit

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp ./other/install.php .
  - cp ./other/install_2-1_mysql.sql .
  - cp ./other/install_2-1_postgresql.sql .
  - cp ./other/Settings.php .
  - cp ./Settings.php ./Settings_bak.php
  - cp ./other/readme.html .
  - cp ./other/db_last_error.php .


script:
  - php vendor/bin/phpunit
  - psql travis_ci_test -c 'select count(*) from smf_members;' -U postgres
